name: inso-cli-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: Setup inso
        uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1

      - name: Print inso version
        run: inso --version

      # - name: Run with dot report
      #   run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./Tadeu-QualityEagles-Collection.yaml --reporter dot
      # - name: Run with list report
      #   run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./Tadeu-QualityEagles-Collection.yaml --reporter list
      - name: Run with spec report (default)
        run: inso run collection NEW-Tadeu-QualityEagles-Collection_Insomnia -w ./NEW-Tadeu-QualityEagles-Collection_Insomnia.yaml --reporter spec
      # - name: Run with min report
      #   run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./Tadeu-QualityEagles-Collection.yaml --reporter min
      # - name: Run with progress report
      #   run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./Tadeu-QualityEagles-Collection.yaml --reporter progress