name: inso-cli-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      - name: Setup inso
        uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1

      - name: Print inso version
        run: inso --version

      - name: Run insomnia test suite
        # run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./TEST-Tadeu-QualityEagles-Collection_Insomnia.yaml
        run: |
          inso run test \
            --spec Tadeu-QualityEagles-Collection.yaml \
            --data Tadeu-QualityEagles-Collection.yaml \
            --format junit \
            --output test-results.xml