name: inso-cli-pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Print working directory
        run: pwd
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      # #     node-version: '20.x'
      #   # uses: Kong/setup-inso@cf1bf7b12e5d0092399c79025c09eba54d8182f7
      # - name: Setup inso
      #   uses: kong/setup-inso@v2
      #   with:
      #     inso-version: 10.3.1
      #   # uses: Kong/setup-inso@9857463605f7018f0b10aacdb11b10e3823ce18b
      #   # # uses: Kong/setup-inso/releases/tag/v2.0.0
      #   # with:
      #   #   inso-version: 10.3.1
      #     # compression: gzip


      # a) setup-inso@v2
      - name: Setup inso
        uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1

      # # a) setup-inso@v2 with wrapper
      # - uses: kong/setup-inso@v2
      #   with:
      #     inso-version: 10.3.1
      #     wrapper: true
      # - run: inso --version
      #   id: inso_version
      # - run: echo '${{ toJson(steps.inso_version.outputs) }}'



      - name: Print inso version
        run: inso --version

      - name: list files
        run: ls -ltr $pwd
      - name: cat README.md
        run: cat README.md

      # - name: Print testesteststestestes
      #   run: ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Print inso help
      #   run: inso --help

      # - name: Print inso run help
      #   run: inso run --help

      # - name: Verify directory
      #   run: |
      #     ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Enter into
      #   run: cd /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Change permission
      #   run: chmod 777 /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data/*

      # - name: Verify directory again
      #   run: |
      #     ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Verify relative path
      #   run: |
      #     ls -la ./insomnia-data

      # - name: Verify CI dir
      #   run: |
      #     ls -la /home/runner/work/

      # - name: Verify CI app dir
      #   run: |
      #     ls -la /home/runner/work/eagles-postman-newman/

      # - name: Verify CI app data
      #   run: |
      #     ls -la /home/runner/work/eagles-postman-newman/eagles-postman-newman/insomnia-data

      # - name: Verify root
      #   run: |
      #     ls -la ~/

      # - name: Verify .config
      #   run: |
      #     ls -la ~/.config/

      # # ls -la ~/.config/Insomnia
      # - name: Verify .config/GitHub/ActionsService/8.0
      #   run: |
      #     ls -la ~/.config/GitHub/ActionsService/8.0

      # - name: Verify .config/configstore
      #   run: |
      #     ls -la ~/.config/configstore

      # - name: Run script 1
      #   run: inso run collection wrk_bd9716d353474b419167322690b72561 --env wrk_a52871109e74470492e82991932be508 --workingDir /home/runner/work/inso-cli-pipeline/inso-cli-pipeline --verbose --printOptions --ci
        # run: inso run test req_949acd37e4764c7fac290d62681e97e7 --workingDir /home/runner/work/inso-cli-pipeline/inso-cli-pipeline --verbose --printOptions --ci
        # run: inso run test wrk_bd9716d353474b419167322690b72561 --env env_088d03b20fd1b1b242cd8972065cee44198dc93e --workingDir /home/runner/work/inso-cli-pipeline --verbose --printOptions --ci
        # run: inso run test wrk_bd9716d353474b419167322690b72561 --env env_088d03b20fd1b1b242cd8972065cee44198dc93e --workingDir $pwd --verbose --printOptions --ci
      # - name: Run script 2
      #   run: inso run collection wrk_bd9716d353474b419167322690b72561 --workingDir /home/runner/work/inso-cli-pipeline/inso-cli-pipeline --verbose --printOptions --ci
      - name: Run insomnia test suite
        run: inso run collection wrk_1c417c13210e42d1b4da6345a53e6534 -w ./TEST-Tadeu-QualityEagles-Collection_Insomnia.yaml
        # run: inso run collection wrk_7a1bc182abe146bcb732553ae42ae761 --verbose --printOptions --ci
        # run: inso run collection wrk_babb0e6e694647979693649fc368179d --env env_6240d4965c659311762025efd96dd4e6b33e561f --workingDir /home/runner/work/inso-cli-pipeline/inso-cli-pipeline --verbose --printOptions --ci
